### ISSUE TITLE
Change repo name to "eurocsdms"

### ISSUE THREAD

**Issue by BSchilperoort** [eWaterCycle/eurocsdms_workshop#1]
Currently the github pages url is: http://www.ewatercycle.org/eurocsdms_ewatercycle_workshop
If we change the name of this repo it could be just: `ewatercycle.org/eurocsdms`

@RolfHut

**Comment by RolfHut** [comment]
given that I predict that CEH wants to start an initiative with just that name, I don't want to "claim" it right now on github... Cant we make an html forward (301 ?) to where we want from ewatercycle.org/eurocsdms ?

**Comment by BSchilperoort** [comment]
It would only be a repository under the ewatercycle org.

> Cant we make an html forward (301 ?) to where we want from ewatercycle.org/eurocsdms ?

Not sure if we can... I'll check with Stefan.

Alternatively we can do `ewatercycle.org/eurocsdms-workshop` to make it a bit shorter.

**Comment by RolfHut** [comment]
let's go with eurocsdm-workshop. I'll change the name.

**Comment by RolfHut** [comment]
done
