### ISSUE TITLE
Broken link in example pcrglob run

### ISSUE THREAD

**Issue by BSchilperoort** [eWaterCycle/eurocsdms_workshop#6]
Under the header [Load forcing data](http://www.ewatercycle.org/eurocsdms_workshop/main/oneModel/additional/pcrglobwb/example_model_run_pcrglobwb.html#load-forcing-data), hyperlink to "preprocessing examples" is broken.

It should point to https://ewatercycle.readthedocs.io/en/latest/user_guide/02_forcing.html

**Comment by RolfHut** [comment]
already fixed by the merging of the cleanup Rolf branch.
